services:
  - type: web
    name: n8n-odontia
    env: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: WEBHOOK_URL
        value: https://n8n-odontia.onrender.com/
      - key: N8N_DEFAULT_BINARY_DATA_MODE
        value: filesystem
    disk:
      name: n8n-data
      mountPath: /home/node/.n8n
      sizeGB: 1
